"""Tests for the reward validator.

Covers the 7 checks performed by RewardValidator:
1. syntax
2. imports
3. rewards_cfg_class
4. rewterm_calls
5. func_references
6. weight_ranges (warnings)
7. common_mistakes (warnings)

Plus an integration test: code generated by RewardSynthesizer must pass.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

_pkg_root = Path(__file__).resolve().parent.parent
if str(_pkg_root) not in sys.path:
    sys.path.insert(0, str(_pkg_root))

from scripts.reward_validator import RewardValidator
from scripts.reward_synthesizer import RewardSynthesizer


# ------------------------------------------------------------------
# Fixtures: minimal valid code and a validator instance
# ------------------------------------------------------------------

VALID_CODE = '''\
"""Minimal valid reward config for testing."""
import math
import torch
from isaaclab.managers import RewardTermCfg as RewTerm, SceneEntityCfg
from isaaclab.utils import configclass
import isaaclab.envs.mdp as mdp
import isaaclab_tasks.manager_based.locomotion.velocity.mdp as mdp_loc


@configclass
class RewardsCfg:
    """Test config."""

    track_lin_vel_xy_exp = RewTerm(
        func=mdp.track_lin_vel_xy_exp,
        weight=1.0,
        params={
            "std": math.sqrt(0.25),
            "command_name": "base_velocity",
        },
    )

    track_ang_vel_z_exp = RewTerm(
        func=mdp.track_ang_vel_z_exp,
        weight=0.5,
        params={
            "std": math.sqrt(0.25),
            "command_name": "base_velocity",
        },
    )

    lin_vel_z_l2 = RewTerm(
        func=mdp.lin_vel_z_l2,
        weight=-2.0,
    )

    feet_air_time = RewTerm(
        func=mdp_loc.feet_air_time,
        weight=0.125,
        params={
            "threshold": 0.5,
            "command_name": "base_velocity",
            "sensor_cfg": SceneEntityCfg("contact_forces", body_names=".*FOOT"),
        },
    )
'''


@pytest.fixture
def validator() -> RewardValidator:
    return RewardValidator()


# ------------------------------------------------------------------
# Check 1: syntax
# ------------------------------------------------------------------

class TestSyntaxCheck:
    def test_valid_syntax_passes(self, validator):
        result = validator.validate_code(VALID_CODE)
        assert "syntax" in result["checks"]
        # Syntax itself doesn't fail (other checks may)
        assert not any("Syntax error" in e for e in result["errors"])

    def test_invalid_syntax_caught(self, validator):
        bad_code = "def broken(:\n    pass"
        result = validator.validate_code(bad_code)
        assert result["valid"] is False
        assert any("Syntax error" in e for e in result["errors"])

    def test_syntax_error_short_circuits(self, validator):
        # If syntax fails, subsequent checks shouldn't run
        result = validator.validate_code("def broken(:")
        # Only syntax check should have run
        assert result["checks"] == ["syntax"]


# ------------------------------------------------------------------
# Check 2: imports
# ------------------------------------------------------------------

class TestImportsCheck:
    def test_all_required_imports_present(self, validator):
        result = validator.validate_code(VALID_CODE)
        for imp in ("configclass", "RewTerm", "mdp"):
            assert not any(f"Missing required import: {imp}" in e for e in result["errors"])

    def test_missing_configclass_caught(self, validator):
        code = VALID_CODE.replace(
            "from isaaclab.utils import configclass",
            "from isaaclab.utils import something_else",
        )
        result = validator.validate_code(code)
        assert any("Missing required import: configclass" in e for e in result["errors"])

    def test_missing_rewterm_caught(self, validator):
        code = VALID_CODE.replace(
            "RewardTermCfg as RewTerm",
            "RewardTermCfg as SomethingElse",
        )
        result = validator.validate_code(code)
        assert any("Missing required import: RewTerm" in e for e in result["errors"])

    def test_missing_mdp_caught(self, validator):
        code = VALID_CODE.replace(
            "import isaaclab.envs.mdp as mdp",
            "import isaaclab.envs.mdp as something_else",
        )
        result = validator.validate_code(code)
        assert any("Missing required import: mdp" in e for e in result["errors"])

    def test_import_with_asname_recognized(self, validator):
        # `import x as y` should register y
        code = VALID_CODE.replace(
            "import isaaclab.envs.mdp as mdp",
            "import isaaclab.envs.mdp as mdp  # aliased",
        )
        result = validator.validate_code(code)
        assert not any("Missing required import: mdp" in e for e in result["errors"])


# ------------------------------------------------------------------
# Check 3: RewardsCfg class structure
# ------------------------------------------------------------------

class TestRewardsCfgClassCheck:
    def test_valid_class_detected(self, validator):
        result = validator.validate_code(VALID_CODE)
        assert "rewards_cfg_class" in result["checks"]
        assert not any("RewardsCfg class" in e for e in result["errors"])

    def test_missing_class_caught(self, validator):
        code = VALID_CODE.replace("class RewardsCfg:", "class NotRewardsCfg:")
        result = validator.validate_code(code)
        assert any("RewardsCfg class not found" in e for e in result["errors"])

    def test_missing_configclass_decorator_caught(self, validator):
        code = VALID_CODE.replace("@configclass\n", "")
        result = validator.validate_code(code)
        assert any("missing @configclass decorator" in e for e in result["errors"])


# ------------------------------------------------------------------
# Check 4: RewTerm calls
# ------------------------------------------------------------------

class TestRewTermCallsCheck:
    def test_valid_rewterms_pass(self, validator):
        result = validator.validate_code(VALID_CODE)
        assert not any("missing 'func' field" in e for e in result["errors"])
        assert not any("missing 'weight' field" in e for e in result["errors"])

    def test_rewterm_missing_func_caught(self, validator):
        code = VALID_CODE.replace(
            "func=mdp.track_lin_vel_xy_exp,",
            "",
        )
        result = validator.validate_code(code)
        assert any("missing 'func' field" in e for e in result["errors"])

    def test_rewterm_missing_weight_caught(self, validator):
        # Remove the weight= line from one RewTerm
        code = VALID_CODE.replace(
            "weight=1.0,\n",
            "\n",
            1,  # only first occurrence
        )
        result = validator.validate_code(code)
        assert any("missing 'weight' field" in e for e in result["errors"])


# ------------------------------------------------------------------
# Check 5: Function references
# ------------------------------------------------------------------

class TestFuncReferencesCheck:
    def test_valid_mdp_functions_pass(self, validator):
        result = validator.validate_code(VALID_CODE)
        assert not any("not in isaaclab.envs.mdp builtins" in e for e in result["errors"])

    def test_typo_in_builtin_function_caught(self, validator):
        # track_lin_vel_xy_exp -> track_lin_vel_xy_ex (typo)
        code = VALID_CODE.replace(
            "mdp.track_lin_vel_xy_exp",
            "mdp.track_lin_vel_xy_ex",
        )
        result = validator.validate_code(code)
        assert any("not in isaaclab.envs.mdp builtins" in e for e in result["errors"])

    def test_custom_function_not_flagged(self, validator):
        # mdp_loc.feet_air_time is in mdp_loc, not mdp — should not be flagged
        result = validator.validate_code(VALID_CODE)
        assert not any("feet_air_time" in e and "not in isaaclab" in e for e in result["errors"])


# ------------------------------------------------------------------
# Check 6: Weight ranges (warnings)
# ------------------------------------------------------------------

class TestWeightRangesCheck:
    def test_normal_weights_no_warning(self, validator):
        result = validator.validate_code(VALID_CODE)
        # Standard weights shouldn't trigger range warnings
        range_warnings = [w for w in result["warnings"] if "may be outside" in w]
        assert len(range_warnings) == 0

    def test_extreme_weight_triggers_warning(self, validator):
        # weight=10000.0 is 10000x the default 1.0
        code = VALID_CODE.replace(
            "weight=1.0,\n        params={\n            \"std\": math.sqrt(0.25),",
            "weight=10000.0,\n        params={\n            \"std\": math.sqrt(0.25),",
        )
        result = validator.validate_code(code)
        # May or may not trigger depending on pattern matching, but at least check it runs
        assert isinstance(result["warnings"], list)


# ------------------------------------------------------------------
# Check 7: Common mistakes (warnings)
# ------------------------------------------------------------------

class TestCommonMistakesCheck:
    def test_velocity_tracking_without_command_name_warns(self, validator):
        # Remove command_name from the first velocity tracking term only.
        # The second term (track_ang_vel_z_exp) still has command_name, but
        # the validator should still flag the first.
        code = VALID_CODE.replace(
            '            "std": math.sqrt(0.25),\n            "command_name": "base_velocity",\n        },\n    )\n\n    track_ang_vel_z_exp',
            '            "std": math.sqrt(0.25),\n        },\n    )\n\n    track_ang_vel_z_exp',
        )
        result = validator.validate_code(code)
        assert any("missing 'command_name'" in w for w in result["warnings"])

    def test_velocity_tracking_without_std_warns(self, validator):
        code = VALID_CODE.replace(
            '"std": math.sqrt(0.25),\n            "command_name": "base_velocity",',
            '"command_name": "base_velocity",',
        )
        result = validator.validate_code(code)
        assert any("missing 'std'" in w for w in result["warnings"])

    def test_feet_air_time_without_threshold_warns(self, validator):
        code = VALID_CODE.replace(
            '"threshold": 0.5,',
            '',
        )
        result = validator.validate_code(code)
        assert any("missing 'threshold'" in w for w in result["warnings"])

    def test_positive_weight_on_penalty_warns(self, validator):
        # lin_vel_z_l2 is a penalty; weight should be negative
        code = VALID_CODE.replace(
            "func=mdp.lin_vel_z_l2,\n        weight=-2.0,",
            "func=mdp.lin_vel_z_l2,\n        weight=2.0,",
        )
        result = validator.validate_code(code)
        assert any("penalty has positive weight" in w for w in result["warnings"])

    def test_negative_weight_on_tracking_warns(self, validator):
        code = VALID_CODE.replace(
            "func=mdp.track_lin_vel_xy_exp,\n        weight=1.0,",
            "func=mdp.track_lin_vel_xy_exp,\n        weight=-1.0,",
        )
        result = validator.validate_code(code)
        assert any("task reward has non-positive weight" in w for w in result["warnings"])


# ------------------------------------------------------------------
# Result structure
# ------------------------------------------------------------------

class TestResultStructure:
    def test_returns_valid_flag(self, validator):
        result = validator.validate_code(VALID_CODE)
        assert "valid" in result
        assert isinstance(result["valid"], bool)

    def test_returns_checks_list(self, validator):
        result = validator.validate_code(VALID_CODE)
        assert "checks" in result
        assert isinstance(result["checks"], list)
        assert len(result["checks"]) >= 4

    def test_returns_errors_list(self, validator):
        result = validator.validate_code(VALID_CODE)
        assert "errors" in result
        assert isinstance(result["errors"], list)

    def test_returns_warnings_list(self, validator):
        result = validator.validate_code(VALID_CODE)
        assert "warnings" in result
        assert isinstance(result["warnings"], list)

    def test_valid_code_has_no_errors(self, validator):
        result = validator.validate_code(VALID_CODE)
        assert result["valid"] is True, f"Errors: {result['errors']}"
        assert len(result["errors"]) == 0


# ------------------------------------------------------------------
# File validation
# ------------------------------------------------------------------

class TestValidateFile:
    def test_validate_existing_file(self, validator, tmp_path):
        f = tmp_path / "reward.py"
        f.write_text(VALID_CODE, encoding="utf-8")
        result = validator.validate_file(f)
        assert result["valid"] is True

    def test_validate_missing_file(self, validator, tmp_path):
        result = validator.validate_file(tmp_path / "nonexistent.py")
        assert result["valid"] is False
        assert any("File not found" in e for e in result["errors"])

    def test_validate_file_accepts_string_path(self, validator, tmp_path):
        f = tmp_path / "reward.py"
        f.write_text(VALID_CODE, encoding="utf-8")
        result = validator.validate_file(str(f))
        assert result["valid"] is True


# ------------------------------------------------------------------
# Integration: synthesizer output must pass validation
# ------------------------------------------------------------------

class TestSynthesizerValidatorIntegration:
    def test_synthesized_velocity_reward_passes_validation(self):
        synth = RewardSynthesizer()
        result = synth.synthesize(
            "train quadruped to walk forward at 1 m/s, keep stable",
            validate=True,
        )
        assert result.validation is not None
        assert result.validation["valid"], (
            f"Synthesized code failed validation:\n"
            f"Errors: {result.validation.get('errors', [])}\n"
            f"Warnings: {result.validation.get('warnings', [])}"
        )

    def test_synthesized_rough_terrain_reward_passes_validation(self):
        synth = RewardSynthesizer()
        result = synth.synthesize(
            "train quadruped to walk over rough terrain with stairs",
            validate=True,
        )
        assert result.validation is not None
        assert result.validation["valid"], (
            f"Errors: {result.validation.get('errors', [])}"
        )

    def test_synthesized_chinese_task_passes_validation(self):
        synth = RewardSynthesizer()
        result = synth.synthesize(
            "训练四足以 1 m/s 前进，保持身体水平稳定",
            validate=True,
        )
        assert result.validation is not None
        assert result.validation["valid"]

    def test_synthesized_with_optional_passes_validation(self):
        synth = RewardSynthesizer()
        result = synth.synthesize(
            "train quadruped to walk forward at 1 m/s",
            include_optional=True,
            validate=True,
        )
        assert result.validation is not None
        assert result.validation["valid"]

    def test_synthesized_with_weight_override_passes_validation(self):
        synth = RewardSynthesizer()
        result = synth.synthesize(
            "train quadruped to walk forward",
            config_overrides={"linear_velocity_tracking": {"weight": 2.0}},
            validate=True,
        )
        assert result.validation is not None
        assert result.validation["valid"]


# ------------------------------------------------------------------
# Edge cases (input boundaries, error handling)
# ------------------------------------------------------------------

class TestEdgeCases:
    def test_none_code_raises_type_error(self, validator):
        with pytest.raises(TypeError, match="code"):
            validator.validate_code(None)

    def test_empty_string_code_returns_invalid(self, validator):
        """Empty string parses as empty module — should fail imports check."""
        result = validator.validate_code("")
        assert result["valid"] is False
        assert any("configclass" in e for e in result["errors"])

    def test_weight_zero_triggers_warning(self, validator):
        code = VALID_CODE.replace(
            "weight=1.0",
            "weight=0.0",
        )
        result = validator.validate_code(code)
        # weight=0 for a tracking term should trigger a warning
        assert any("0" in w or "zero" in w.lower() for w in result["warnings"])

    def test_weight_nan_does_not_crash(self, validator):
        """NaN weight should not crash the validator — skip or warn."""
        code = VALID_CODE.replace(
            "weight=1.0",
            "weight=float('nan')",
        )
        # Should not raise
        result = validator.validate_code(code)
        assert isinstance(result["valid"], bool)

    def test_validate_file_with_directory_raises(self, validator, tmp_path):
        """Passing a directory path should raise a clear error, not PermissionError."""
        with pytest.raises((IsADirectoryError, ValueError, OSError)):
            validator.validate_file(tmp_path)
