# Auto-generated by Isaac Lab RL Co-pilot (reward_synthesizer.py)
# Template: locomotion_full_cfg.py.tmpl
# Task type: locomotion (quadruped / biped)
# Task: train quadruped to walk forward at 1 m/s, keep stable, minimize energy
# Generated: 2026-07-09 20:09:46
#
# Composed patterns:
#   - linear_velocity_tracking
#   - angular_velocity_tracking
#   - lin_vel_z_l2
#   - ang_vel_xy_l2
#   - joint_torques_l2
#   - joint_acc_l2
#   - action_rate_l2
#   - feet_air_time
#   - undesired_contacts
#
# Weight source: reward_patterns.json defaults + PATTERN_DEFAULTS
#
# To customize: edit weights/params below, or re-run synthesizer with different params.
# Validation: run `python scripts/reward_validator.py --file <this_file>` to check.

"""Reward configuration for: train quadruped to walk forward at 1 m/s, keep stable, minimize energy

This file was generated by the Isaac Lab RL Co-pilot. It composes curated
reward patterns from the legged_gym / IsaacLab ecosystem into a complete
RewardsCfg suitable for mounting on a ManagerBasedRLEnvCfg.

Reference: see resources/reward_patterns.json for pattern details and
references/eureka_comparison.md for how this differs from Eureka.
"""

import math

import torch

from isaaclab.managers import RewardTermCfg as RewTerm, SceneEntityCfg
from isaaclab.utils import configclass
import isaaclab.envs.mdp as mdp
import isaaclab_tasks.manager_based.locomotion.velocity.mdp as mdp_loc


@configclass
class RewardsCfg:
    """Reward configuration for: train quadruped to walk forward at 1 m/s, keep stable, minimize energy

    Pattern composition (9 terms):
    - linear_velocity_tracking: weight=1.0
    - angular_velocity_tracking: weight=0.5
    - lin_vel_z_l2: weight=-2.0
    - ang_vel_xy_l2: weight=-0.05
    - joint_torques_l2: weight=-1e-05
    - joint_acc_l2: weight=-2.5e-07
    - action_rate_l2: weight=-0.01
    - feet_air_time: weight=0.125
    - undesired_contacts: weight=-1.0
    """

    # ============================================================
    # Task Rewards (positive weight) — main objective
    # ============================================================
    # Linear velocity tracking (main task reward)
    # Pattern: linear_velocity_tracking
    # Purpose: track commanded forward/lateral velocity
    # Formula: r = exp(-||v_cmd - v_base||^2 / std^2)
    track_lin_vel_xy_exp = RewTerm(
        func=mdp.track_lin_vel_xy_exp,
        weight=1.0,
        params={
            "std": math.sqrt(0.25),
            "command_name": "base_velocity",
        },
    )

    # Angular velocity tracking (auxiliary task reward)
    # Pattern: angular_velocity_tracking
    # Purpose: track commanded yaw rate
    # Formula: r = exp(-(omega_z_cmd - omega_z_base)^2 / std^2)
    track_ang_vel_z_exp = RewTerm(
        func=mdp.track_ang_vel_z_exp,
        weight=0.5,
        params={
            "std": math.sqrt(0.25),
            "command_name": "base_velocity",
        },
    )

    # ============================================================
    # Stability Penalties (negative weight) — keep robot upright
    # ============================================================
    # Penalize z-axis linear velocity (prevent vertical bouncing)
    lin_vel_z_l2 = RewTerm(
        func=mdp.lin_vel_z_l2,
        weight=-2.0,
    )

    # Penalize roll/pitch angular velocity (keep heading stable)
    ang_vel_xy_l2 = RewTerm(
        func=mdp.ang_vel_xy_l2,
        weight=-0.05,
    )


    # ============================================================
    # Energy & Smoothness Penalties — protect hardware, sim-to-real
    # ============================================================
    # Penalize joint torques (energy consumption)
    # Pattern: joint_torques_l2
    # Note: weight is tiny (-1e-5) because torque^2 is large (~1e5)
    joint_torques_l2 = RewTerm(
        func=mdp.joint_torques_l2,
        weight=-1e-05,
    )

    # Penalize joint acceleration (motion smoothness)
    joint_acc_l2 = RewTerm(
        func=mdp.joint_acc_l2,
        weight=-2.5e-07,
    )

    # Penalize action rate (control smoothness, sim-to-real critical)
    # Pattern: action_rate_l2
    # Formula: r = -||a_t - a_{t-1}||^2
    action_rate_l2 = RewTerm(
        func=mdp.action_rate_l2,
        weight=-0.01,
    )

    # ============================================================
    # Gait Reward (positive weight) — encourage rhythmic stepping
    # ============================================================
    # Reward feet air time above threshold (encourages trot gait)
    # Pattern: feet_air_time
    # Formula: r = sum(max(0, t_air - threshold)) on first contact
    feet_air_time = RewTerm(
        func=mdp_loc.feet_air_time,
        weight=0.125,
        params={
            "threshold": 0.5,
            "command_name": "base_velocity",
            "sensor_cfg": SceneEntityCfg("contact_forces", body_names=".*FOOT"),
        },
    )

    # ============================================================
    # Safety Penalties (negative weight) — prevent damage
    # ============================================================
    # Penalize undesired contacts (e.g., thigh hitting ground)
    undesired_contacts = RewTerm(
        func=mdp.undesired_contacts,
        weight=-1.0,
        params={
            "sensor_cfg": SceneEntityCfg("contact_forces", body_names=".*THIGH"),
            "threshold": 1.0,
        },
    )



    # ============================================================
    # Optional terms (weight=0, disabled but kept for experimentation)
    # ============================================================
